// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqaVbEW8UOMTOMhKvh9-4yDN2JicRFPx4',
    appId: '1:482948449877:web:1230b460741c188986f6dc',
    messagingSenderId: '482948449877',
    projectId: 'xygen-dashboard',
    authDomain: 'xygen-dashboard.firebaseapp.com',
    storageBucket: 'xygen-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zi-qHCozRXixtXxP4nnjXLyzhQqoXAY',
    appId: '1:482948449877:android:80d4adc0fed9ba3086f6dc',
    messagingSenderId: '482948449877',
    projectId: 'xygen-dashboard',
    storageBucket: 'xygen-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgM31T7CvZVlFb0S75O2OnwusZOw1KSls',
    appId: '1:482948449877:ios:4f5ca323b201508186f6dc',
    messagingSenderId: '482948449877',
    projectId: 'xygen-dashboard',
    storageBucket: 'xygen-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.oxygenDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgM31T7CvZVlFb0S75O2OnwusZOw1KSls',
    appId: '1:482948449877:ios:4f5ca323b201508186f6dc',
    messagingSenderId: '482948449877',
    projectId: 'xygen-dashboard',
    storageBucket: 'xygen-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.oxygenDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqaVbEW8UOMTOMhKvh9-4yDN2JicRFPx4',
    appId: '1:482948449877:web:7075e2598c4d323886f6dc',
    messagingSenderId: '482948449877',
    projectId: 'xygen-dashboard',
    authDomain: 'xygen-dashboard.firebaseapp.com',
    storageBucket: 'xygen-dashboard.firebasestorage.app',
  );
}
